config/routes.rb
Rails.application.routes.draw do
  resources :portions
  resources :sales
  resources :products
  resources :payment_methods
  resources :customers
  root 'home#index'

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
	validates_presence_of :name
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:name, :description)
    end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<div class="row">
  <%= form_for(@payment_method) do |f| %>
    <% if @payment_method.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

        <ul>
        <% @payment_method.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row">
      <div class="input-field col s6">
        <%= f.label :name, "Nome" %><br>
        <%= f.text_field :name %>
      </div>
      <div class="input-field col s6">
        <%= f.label :description, "Descrição" %><br>
        <%= f.text_field :description %>
      </div>
    </div>

    <div class="row">
      <div class="col s12">
        <button class="btn waves-effect waves-light modal-close" type="submit" name="action">Salvar
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @payment_method %> |
<%= link_to 'Voltar', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Lista de métodos de pagamento</h2>

<div class="row">
  <table class="striped">
    <thead>
      <tr>
        <th data-field="name">Nome</th>
        <th data-field="Description">Descrição</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @payment_methods.each do |payment_method| %>
        <tr>
          <td><%= payment_method.name %></td>
          <td><%= payment_method.description %></td>
          <td><%= link_to 'Mostrar', payment_method %></td>
          <td><%= link_to 'Editar', edit_payment_method_path(payment_method) %></td>
          <td><%= link_to 'Excluir', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'Nova Forma de pagamento', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Voltar', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_method.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @payment_method.description %>
</p>

<%= link_to 'Editar', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Voltar', payment_methods_path %>