config/routes.rb
Rails.application.routes.draw do
  resources :portions
  resources :sales
  resources :products
  resources :payment_methods
  resources :customers
  root 'home#index'

end

app/models/portion.rb
class Portion < ActiveRecord::Base
  belongs_to :Sale
  validates_presence_of :Sale
end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController
  before_action :set_portion, only: [:show, :edit, :update, :destroy]

  # GET /portions
  # GET /portions.json
  def index
    @portions = Portion.all
  end

  # GET /portions/1
  # GET /portions/1.json
  def show
  end

  # GET /portions/new
  def new
    @portion = Portion.new
  end

  # GET /portions/1/edit
  def edit
  end

  # POST /portions
  # POST /portions.json
  def create
    @portion = Portion.new(portion_params)

    respond_to do |format|
      if @portion.save
        format.html { redirect_to @portion, notice: 'Portion was successfully created.' }
        format.json { render :show, status: :created, location: @portion }
      else
        format.html { render :new }
        format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portions/1
  # PATCH/PUT /portions/1.json
  def update
    respond_to do |format|
      if @portion.update(portion_params)
        format.html { redirect_to @portion, notice: 'Portion was successfully updated.' }
        format.json { render :show, status: :ok, location: @portion }
      else
        format.html { render :edit }
        format.json { render json: @portion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portions/1
  # DELETE /portions/1.json
  def destroy
    @portion.destroy
    respond_to do |format|
      format.html { redirect_to portions_url, notice: 'Portion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portion
      @portion = Portion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portion_params
      params.require(:portion).permit(:portion_date, :Sale_id, :name, :number, :is_paid)
    end
end

app/helpers/portions_helper.rb
module PortionsHelper
end

app/views/portions/_form.html.erb
<%= form_for(@portion) do |f| %>
  <% if @portion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portion.errors.count, "error") %> prohibited this portion from being saved:</h2>

      <ul>
      <% @portion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :portion_date %><br>
    <%= f.date_select :portion_date %>
  </div>
  <div class="field">
    <%= f.label :Sale_id %><br>
    <%= f.text_field :Sale_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :is_paid %><br>
    <%= f.check_box :is_paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portions/edit.html.erb
<h1>Editing Portion</h1>

<%= render 'form' %>

<%= link_to 'Show', @portion %> |
<%= link_to 'Back', portions_path %>

app/views/portions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Portions</h1>

<table>
  <thead>
    <tr>
      <th>Portion date</th>
      <th>Sale</th>
      <th>Name</th>
      <th>Number</th>
      <th>Is paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @portions.each do |portion| %>
      <tr>
        <td><%= portion.portion_date %></td>
        <td><%= portion.Sale %></td>
        <td><%= portion.name %></td>
        <td><%= portion.number %></td>
        <td><%= portion.is_paid %></td>
        <td><%= link_to 'Show', portion %></td>
        <td><%= link_to 'Edit', edit_portion_path(portion) %></td>
        <td><%= link_to 'Destroy', portion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Portion', new_portion_path %>

app/views/portions/new.html.erb
<h1>New Portion</h1>

<%= render 'form' %>

<%= link_to 'Back', portions_path %>

app/views/portions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Portion date:</strong>
  <%= @portion.portion_date %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @portion.Sale %>
</p>

<p>
  <strong>Name:</strong>
  <%= @portion.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @portion.number %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @portion.is_paid %>
</p>

<%= link_to 'Edit', edit_portion_path(@portion) %> |
<%= link_to 'Back', portions_path %>