config/routes.rb
Rails.application.routes.draw do
  resources :portions
  resources :sales
  resources :products
  resources :payment_methods
  resources :customers
  root 'home#index'

end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :Customer
  belongs_to :PaymentMethod
  has_many :products, through: :saleProducts
  validates_presence_of :Customer, :PaymentMethod, :total
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:Customer_id, :user_id, :sale_date, :total, :PaymentMethod_id, :times, :is_fitpark)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Customer_id %><br>
    <%= f.text_field :Customer_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :sale_date %><br>
    <%= f.date_select :sale_date %>
  </div>
  <div class="field">
    <%= f.label :total %><br>
    <%= f.text_field :total %>
  </div>
  <div class="field">
    <%= f.label :PaymentMethod_id %><br>
    <%= f.text_field :PaymentMethod_id %>
  </div>
  <div class="field">
    <%= f.label :times %><br>
    <%= f.text_field :times %>
  </div>
  <div class="field">
    <%= f.label :is_fitpark %><br>
    <%= f.check_box :is_fitpark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>User</th>
      <th>Sale date</th>
      <th>Total</th>
      <th>Paymentmethod</th>
      <th>Times</th>
      <th>Is fitpark</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.Customer %></td>
        <td><%= sale.user_id %></td>
        <td><%= sale.sale_date %></td>
        <td><%= sale.total %></td>
        <td><%= sale.PaymentMethod %></td>
        <td><%= sale.times %></td>
        <td><%= sale.is_fitpark %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.Customer %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user_id %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<p>
  <strong>Total:</strong>
  <%= @sale.total %>
</p>

<p>
  <strong>Paymentmethod:</strong>
  <%= @sale.PaymentMethod %>
</p>

<p>
  <strong>Times:</strong>
  <%= @sale.times %>
</p>

<p>
  <strong>Is fitpark:</strong>
  <%= @sale.is_fitpark %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>